name: "Build gem"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    outputs:
      gem-name:
        value: ${{ jobs.build.outputs.gem-name-output }}

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      gem-name-output: ${{ steps.build-ruby-gem.outputs.GEM_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install dependencies
        run: gem install bundler
      - run: bundle install
      - name: Run Specs
        run: bundle exec rspec
      - name: Build Gem
        id: build-ruby-gem
        run: |
          gem build toy-ore.gemspec
          echo "::set-output name=GEM_NAME::$(basename toy-ore-*.gem)"
      - name: Upload Gem Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build-ruby-gem.outputs.GEM_NAME }}
          path: toy-ore-*.gem
