name: Release

on:
  release:
    types:
      - released
  workflow_dispatch: {}
jobs:
  build-and-test-ruby-gems:
    uses: fimac/toy_ore_rb/build-gem.yml@main
  publish-gem:
    name: "Publish toy-ore gem"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.build-ruby-gem.outputs.GEM_NAME }}
          shell: bash
          run: gem push ${{ steps.build-ruby-gem.outputs.GEM_NAME }}
